apiVersion: apps/v1
kind: Deployment
metadata:
  name: server-calculadora
spec:
  selector:
    matchLabels:
      app: server-calculadora
  replicas: 1
  template:
    metadata:
      labels:
        app: server-calculadora
    spec:
      containers:
      - name: server
        build: 
          context: ./server
          dockerfile: dockerfile
        env:
        - name: DD_AGENT_HOST
          valueFrom:
            fieldRef:
              fieldPath: status.hostIP
        resources:
          requests:
            memory: "64Mi"
            cpu: "200m"
          limits:
            memory: "128Mi"
            cpu: "500m"
        readinessProbe:
          httpGet:
            path: /
            port: 9666
          initialDelaySeconds: 5
          periodSeconds: 10
        livenessProbe:
          tcpSocket:
            port: 9666
          initialDelaySeconds: 15
          periodSeconds: 20
        ports:
        - containerPort: 9666
      

      containers:
      - name: cliente
        image: ubuntu:latest
        env:
        - name: DD_AGENT_HOST
          valueFrom:
            fieldRef:
              fieldPath: status.hostIP
        resources:
          requests:
            memory: "64Mi"
            cpu: "200m"
          limits:
            memory: "128Mi"
            cpu: "500m"
        readinessProbe:
          httpGet:
            path: /
            port: 8080
          initialDelaySeconds: 5
          periodSeconds: 10
        livenessProbe:
          tcpSocket:
            port: 8080
          initialDelaySeconds: 15
          periodSeconds: 20
        ports:
        - containerPort: 8080